name: Static analysis

on: [workflow_dispatch]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: '.'
